### ISSUE TITLE
[demo] add brush size slider 

### ISSUE THREAD

**Issue by subinium** [hyungkwonko/webtoon-gan#1]
- brush 사이즈를 사용자가 조정할 수 있도록 변경
- 현재 기본 사이즈는 20으로 조정되어 있음

**Comment by hyungkwonko** [comment]
pen size 조정시 밑에 브러시 자국이 생기는 버그

**Comment by subinium** [comment]
- UI적으로 고려하여 해당 brush를 포토샵에서 사용하는 단축키와 유사하게 매칭시켜 코딩 
- `[` 는 brush size 크게, `]`는 brush size 작게 하는 단축키 
- min, max 사이즈 조정
- eraser와 brush 사이즈를 일치시켜 erase도 마찬가지로 size 조정가능
- brush 크기를 가늠하지 못하는 이슈를 해결하기 위해 현재 brush size를 투명한 회색으로 사용하여 보여줌
- 얼굴 방향 전환 등의 내용도 단축키로 변경 예정  
   - 단축키에 대한 설명은 인터페이스에 설명으로 추가 예정


![스크린샷 2021-06-14 오후 10 30 43](https://user-images.githubusercontent.com/16396561/121900285-3b471200-cd60-11eb-986f-82fa9acb88fa.png)
