### ISSUE TITLE
left-right module + image mixing module integration

### ISSUE THREAD

**Issue by subinium** [hyungkwonko/webtoon-gan#11]
- original image를 left-right로 조정
   - slider로 조정 
- 조정된 이미지 + reference + mask로 이미지 생성
- demo flask backend 붙이기

**Comment by subinium** [comment]
- 다음 코드로 실행 가능 (`085000_left_right_boundary.npy`는 따로 업로드할 예정)

``` py
python demo.py --ckpt expr/checkpoints/085000.pt --dataset sketch --boundary expr/semantic_manipulation/left_right/085000_left_right_boundary.npy
```

**Comment by hyungkwonko** [comment]
semantic_manipulation 폴더에 기존 celeba 관련 .npy 지우고 우리 것으로 update 하면 좋을 듯

**Comment by hyungkwonko** [comment]
다음 2개의 모델 update 후 추가적으로 inverted w를 학습하여 진행할 예정
1. 8x8 추가 training
2. 16x16 training

**Comment by hyungkwonko** [comment]
현재 
- lr_neg_indices.npy
- lr_pos_indices.npy

2개에 front에 해당하는 이미지 400개가 random 하게 들어간 상황

Todo:
- 400개 index 제거
- front / left / right 3개로 분리
- filelist2indices.py 업데이트

**Comment by hyungkwonko** [comment]
lr_neg_indices.npy, lr_pos_indices.npy 등 index --> reproduce할 것을 대비해 파일 이름에 대한 정보로 저장해 놓으면 좋을 듯

**Comment by hyungkwonko** [comment]
Demo에서 Extreme한 각도에 대해서 제한하는 것이 필요할 듯

**Comment by subinium** [comment]
해당 추가 이슈는 다른 새로운 이슈로 #16 #17 #18
