### ISSUE TITLE
additional model training

### ISSUE THREAD

**Issue by subinium** [hyungkwonko/webtoon-gan#18]
다음 2개의 모델 update 후 추가적으로 inverted w를 학습하여 진행할 예정

- 8x8 추가 training (현재 85000iter)
- 16x16 training

**Comment by subinium** [comment]
- GPU 4개로 훈련 진행 
- 서버 메모리가 정리되서 그런지 훨씬 빠름 
- 현재 iter당 3.5sec
- `--latent_spatial_size 16`를 추가하여 16by16 map으로 훈련

``` py
python train.py --dataset sketch --train_lmdb data/sketch256/LMDB_train --val_lmdb data/sketch256/LMDB_val --size 256 --save_network_interval 5000 --latent_spatial_size 16
```

**Comment by hyungkwonko** [comment]
8x8 추가 training (85000에서 추가 진행)
- gpu 2개
- 6.3 s / iter

**Comment by hyungkwonko** [comment]
8 x 8 결과 (10만 iter)
- 윙크, 디테일한 묘사, 장신구 등에 대해 recon 성능이 많이 떨어짐
![4_real](https://user-images.githubusercontent.com/37931902/122086878-1c6b7d00-ce3f-11eb-90a0-06ea903197e9.png) ![4_recon](https://user-images.githubusercontent.com/37931902/122086888-1e354080-ce3f-11eb-882c-703467844af1.png)
![11_real](https://user-images.githubusercontent.com/37931902/122086953-2d1bf300-ce3f-11eb-89a1-1f564ab4133c.png) ![11_recon](https://user-images.githubusercontent.com/37931902/122086965-2f7e4d00-ce3f-11eb-8486-342f4c0d36d4.png)

따라서 8 x 8 Training STOP --> 16 x 16 사용 예정

**Comment by hyungkwonko** [comment]
16 x 16  25,000 iter 결과 (수빈 작업)
- 위 결과 보다 iter 수가 훨씬 적음에도 디테일한 묘사가 뛰어남
![KakaoTalk_Photo_2021-06-16-01-12-35](https://user-images.githubusercontent.com/37931902/122087790-16c26700-ce40-11eb-917c-e76325b061a7.png) ![KakaoTalk_Photo_2021-06-16-01-12-31](https://user-images.githubusercontent.com/37931902/122087787-1629d080-ce40-11eb-86a9-58c831c8d385.png)
![KakaoTalk_Photo_2021-06-16-01-12-15](https://user-images.githubusercontent.com/37931902/122087779-132ee000-ce40-11eb-9a81-f8c09d5adf46.png) ![KakaoTalk_Photo_2021-06-16-01-12-20](https://user-images.githubusercontent.com/37931902/122087783-15913a00-ce40-11eb-9cfb-b7ed4e5acc36.png)

**Comment by subinium** [comment]
- reconstruction 및 synthesis의 성능 자체는 8x8 100,000iter보다 16x16 65,000 iter가 좋음
- 다만 방향 조정에 사용되는 interfaceGAN은 8x8이 더 좋음
    - latent size가 4배가 됨과 동시에 데이터가 더 필요한 것으로 필요
    - 현재 실험은 2가지 방향으로 진행중
       - 방향 조정에 사용되는 데이터 레이블링 수 늘리기
       - 데이터셋의 사이즈를 70000개에서 300000개(원본 full)로 사용하여 training
           - ckpt에 전체 데이터셋 수 등이 포함되어 있는 것 같아 처음부터 다시 학습 진행중
