### ISSUE TITLE
Direct Manipulation on Face Direction

### ISSUE THREAD

**Issue by subinium** [hyungkwonko/webtoon-gan#22]
- 얼굴 방향에 대한 움직임을 현재는 slider로 하고 있음
- Direct Manipulation에 맞게 이미지에서 마우스로 드래그하여 회전시키는 Interaction 제안
   - 현재 interaction 보다는 편하면 좋을 듯
   - 단순히 키보드로 좌우 변경시킬 수도 있고, 가능한 것 확인
   - 위아래 얼굴 방향도 사용할 수 있을 듯
- 해당 아이디어에 대한 의견 요청 @hyungkwonko

**Comment by hyungkwonko** [comment]
키보드 사용으로 fix
