### ISSUE TITLE
model memory optimization

### ISSUE THREAD

**Issue by subinium** [hyungkwonko/webtoon-gan#6]
> 모델 경량화와 관련하여 정리하는 이슈

모델을 경량화하는 방법은 다음과 같이 분류되며 다음과 같은 순서로 시도해볼 예정.

- **Quantization(양자화)** : 데이터 해상도 낮추기
- **Pruning(가지치기)** : 중요하지 않는 부분을 가지치기 
- **Distillation(증류)** : 사이즈 작은 모델 재훈련

---

### 모델 훈련 스펙

- `python=3.6.12`
- `pytorch=1.4.0`
- `cuda=10.2`

**Comment by subinium** [comment]
## Quantization 

torch에서 제공하는 quantization은 총 3가지 존재

1. Dynamic Quantization (trained model)
2. Static Quantization (post training)
3. Quantization Aware Training

1. 실험 결과 불가능함 확인 : nn.Linear과 nn.Conv 등 기존에 설게된 layer만 quantized 가능
2. 훈련 전에 세팅하고 훈련을 진행해야 함. (추후 고려)
3. TBD

## Reference 

- https://pytorch.org/blog/introduction-to-quantization-on-pytorch/

**Comment by hyungkwonko** [comment]
다른 task에 집중하기 위해 우선 close
