### ISSUE TITLE
semantic manipulation test

### ISSUE THREAD

**Issue by subinium** [hyungkwonko/webtoon-gan#7]
## 현재 상황

- celeba 데이터셋에 대해 30000개의 1, -1로 이루어진 binary로 semantic 정보를 나누는 것으로 보임
- 그리고 pose 정보는 없음 (안되서 안넣은듯) / categorical face feature만 있음
- interfacegan에서 따로 공개한 내용은 없음 
    - [issue](https://github.com/genforce/interfacegan/issues/46)에 좀 써볼 수 있는 script가 있긴하나 결론적으로는 직접 다 구현해야 함

## TODO

- 현재 24개 landmark에서 계산을 해봐야함
    - 이 [repo](https://github.com/jerryhouuu/Face-Yaw-Roll-Pitch-from-Pose-Estimation-using-OpenCV)의 방법을 참고해볼 예정 
- landmark에서 face pose를 다음과 1과 -1로 전처리하면 되지 않을까 생각됨

### ETC

- pose 정보는 총 3가지 방향으로 구성됨 (yaw, roll, pitch)
- ffhq에서 yaw, roll 실험 [issue](https://github.com/genforce/interfacegan/issues/39)

![image](https://user-images.githubusercontent.com/16396561/120912480-68455600-c6ca-11eb-9061-c6dcb79ba08a.png)

**Comment by hyungkwonko** [comment]
https://github.com/genforce/interfacegan/issues/29#issuecomment-573284561
