### ISSUE TITLE
semantic manipulation - left right

### ISSUE THREAD

**Issue by subinium** [hyungkwonko/webtoon-gan#9]
- left right 레이블을 landmark를 통해 가짜로 생성 (눈중앙과 코 사이의 거리를 비교하여 왼쪽/오른쪽으로 구분)
- semantic_manipulation.py를 사용하여 boundary 생성

**Comment by hyungkwonko** [comment]
Self-Labeling 관련 진행 예정
https://github.com/hyungkwonko/webtoon-gan/projects/1#card-62870786

**Comment by hyungkwonko** [comment]
기존 1차 (수빈 작업) 의 left(+1) / right(-1) 통계
left: 169350
right: 133302

**Comment by hyungkwonko** [comment]
## 2차 레이블링 (Manual labeling) 완료

수빈
- left 1000개

형권
- right_training_left.npy: 1018개 파일 이름 리스트 (왼쪽)
- right_training_front.npy: 426개 파일 이름 리스트 (정면)
- right_training_right.npy: 2026개 파일 이름 리스트 (오른쪽)

## right sample 예시
![right_training_right_result_3](https://user-images.githubusercontent.com/37931902/121797993-b32d1380-cc5e-11eb-9203-5f56a12c89de.jpg)

## left sample 예시
![right_training_left_result_1](https://user-images.githubusercontent.com/37931902/121798015-c93ad400-cc5e-11eb-98c1-7ac82cdb8f76.jpg)
